const posts = [
    {
        id: 1,
        title: '5 Tips para Cuidar tus Plantas de Interior',
        href: '/communities/Plantas/1',
        description: 'Consejos prácticos para mantener tus plantas de interior saludables y vibrantes. Aprende los cuidados básicos y trucos avanzados.',
        date: 'Feb 2, 2023',
        datetime: '2023-02-02',
        category: { title: 'Plantas', href: '/communities/Plantas' },
        author: {
        name: 'Lucía Martínez',
        role: 'Botánica',
        href: '/profile/Lucia-Martinez',
        imageUrl: 'https://images.unsplash.com/photo-1541233349642-6e425fe6190e?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 2,
        title: 'Marketing Digital: Estrategias para el 2024',
        href: '/communities/Marketing/2',
        description: 'Descubre las tendencias clave en marketing digital y cómo aplicarlas para maximizar tu alcance y mejorar conversiones.',
        date: 'Jan 12, 2024',
        datetime: '2024-01-12',
        category: { title: 'Marketing', href: '/communities/Marketing' },
        author: {
        name: 'Carlos Gómez',
        role: 'Estratega de Marketing',
        href: '/profile/Carlos-Gomez',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 3,
        title: 'Las 10 Mejores Canciones del 2023',
        href: '/communities/Musica/3',
        description: 'Una selección de las canciones más populares del año que tienes que escuchar. ¡Descubre tus nuevas canciones favoritas!',
        date: 'Dec 25, 2023',
        datetime: '2023-12-25',
        category: { title: 'Música', href: '/communities/Musica' },
        author: {
        name: 'Ana Pérez',
        role: 'Musicóloga',
        href: '/profile/Ana-Perez',
        imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 4,
        title: 'Cómo Pintar Paisajes con Acuarelas',
        href: '/communities/Pinturas/4',
        description: 'Una guía para principiantes en el arte de pintar paisajes en acuarela. Aprende técnicas y descubre inspiración.',
        date: 'Nov 30, 2023',
        datetime: '2023-11-30',
        category: { title: 'Pinturas', href: '/communities/Pinturas' },
        author: {
        name: 'Roberto Díaz',
        role: 'Artista Visual',
        href: '/profile/Roberto-Diaz',
        imageUrl: 'https://images.unsplash.com/photo-1541233349642-6e425fe6190e?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 5,
        title: 'El Rol del Delantero en el Fútbol Moderno',
        href: '/communities/Futbol/5',
        description: 'Exploramos cómo ha cambiado la función del delantero y su impacto en el juego actual.',
        date: 'Mar 14, 2024',
        datetime: '2024-03-14',
        category: { title: 'Fútbol', href: '/communities/Futbol' },
        author: {
        name: 'Diego Hernández',
        role: 'Analista Deportivo',
        href: '/profile/Diego-Hernandez',
        imageUrl: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 6,
        title: 'Cómo Propagar Suculentas en Casa',
        href: '/communities/Plantas/6',
        description: 'Aprende el proceso sencillo para propagar tus suculentas y crear un jardín vibrante con facilidad.',
        date: 'May 22, 2023',
        datetime: '2023-05-22',
        category: { title: 'Plantas', href: '/communities/Plantas' },
        author: {
        name: 'María López',
        role: 'Horticultora',
        href: '/profile/Maria-Lopez',
        imageUrl: 'https://images.unsplash.com/photo-1551227472-9a17b36c5a8a?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 7,
        title: 'Los 5 Mejores Canales de Música Indie en YouTube',
        href: '/communities/Musica/7',
        description: 'Descubre canales de música indie que están marcando tendencia y ampliando el espectro musical.',
        date: 'Jul 10, 2023',
        datetime: '2023-07-10',
        category: { title: 'Música', href: '/communities/Musica' },
        author: {
        name: 'Juan Herrera',
        role: 'Crítico Musical',
        href: '/profile/Juan-Herrera',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 8,
        title: 'Cómo Crear una Marca Personal en Redes Sociales',
        href: '/communities/Marketing/8',
        description: 'Consejos y estrategias para desarrollar una marca personal efectiva en plataformas sociales.',
        date: 'Apr 18, 2024',
        datetime: '2024-04-18',
        category: { title: 'Marketing', href: '/communities/Marketing' },
        author: {
        name: 'Laura Méndez',
        role: 'Consultora de Marketing',
        href: '/profile/Laura-Mendez',
        imageUrl: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 9,
        title: 'Pintando Retratos en Óleo: Técnicas Clave',
        href: '/communities/Pinturas/9',
        description: 'Descubre técnicas para capturar detalles realistas en tus retratos de óleo.',
        date: 'Oct 10, 2023',
        datetime: '2023-10-10',
        category: { title: 'Pinturas', href: '/communities/Pinturas' },
        author: {
        name: 'Sofía Sánchez',
        role: 'Pintora',
        href: '/profile/Sofia-Sanchez',
        imageUrl: 'https://images.unsplash.com/photo-1591845512059-c52c70111e01?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    },
    {
        id: 10,
        title: 'Preparación Física en Fútbol para Jóvenes Jugadores',
        href: '/communities/Futbol/10',
        description: 'Un enfoque en el entrenamiento físico para futbolistas en desarrollo y su impacto en el rendimiento.',
        date: 'Aug 1, 2024',
        datetime: '2024-08-01',
        category: { title: 'Fútbol', href: '/communities/Futbol' },
        author: {
        name: 'Pablo Reyes',
        role: 'Preparador Físico',
        href: '/profile/Pablo-Reyes',
        imageUrl: 'https://images.unsplash.com/photo-1520966871756-65871d879b07?auto=format&fit=facearea&w=256&h=256&q=80',
        },
    }  
];

export default posts;
  